from __future__ import annotations

import httpx

from app.schemas import JobPosting
from app.sources.linkedin import search_companies


NAME = "fortune500"
LABEL = "Fortune 500 (via LinkedIn guest search)"

FORTUNE_500_ALIAS_GROUPS: tuple[tuple[str, ...], ...] = (
    # Big tech / FAANG+
    ("walmart",),
    ("amazon",),
    ("apple",),
    ("alphabet", "google"),
    ("microsoft",),
    ("meta",),
    ("netflix",),
    ("tesla",),
    ("nvidia", "nvidea"),
    ("intel",),
    ("oracle",),
    ("qualcomm",),
    ("adobe",),
    ("salesforce",),
    ("cisco",),
    ("ibm",),
    ("dell", "dell technologies"),
    ("hp", "hewlett packard", "hewlett-packard"),
    ("hpe", "hewlett packard enterprise"),
    ("vmware",),
    ("servicenow",),
    ("workday",),
    ("intuit",),
    ("sap",),
    # Consumer / retail
    ("nike",),
    ("cvs health", "cvs"),
    ("costco",),
    ("home depot", "the home depot"),
    ("lowes", "lowe's"),
    ("target",),
    ("starbucks",),
    ("mcdonalds", "mcdonald's"),
    ("disney", "the walt disney company", "walt disney"),
    # Logistics
    ("ups", "united parcel service"),
    ("fedex",),
    # Finance / payments
    ("visa",),
    ("mastercard",),
    ("paypal",),
    ("at&t", "att", "at t"),
    ("verizon",),
    ("t-mobile", "tmobile"),
    ("goldman sachs", "goldmansachs"),
    ("jpmorgan chase", "jpmorgan", "jp morgan"),
    ("bank of america",),
    ("wells fargo",),
    ("citigroup", "citi"),
    ("morgan stanley",),
    ("american express", "amex"),
    ("blackrock",),
    ("capital one",),
    # Consulting / services
    ("deloitte",),
    ("accenture",),
    ("kpmg",),
    ("ey", "ernst & young", "ernst and young"),
    ("pwc", "pricewaterhousecoopers"),
    ("mckinsey", "mckinsey & company"),
    ("bain", "bain & company"),
    ("boston consulting", "bcg"),
    # Industrial / auto
    ("boeing",),
    ("ford",),
    ("general motors", "gm"),
    ("honeywell",),
    ("3m",),
    ("ge", "general electric"),
    ("caterpillar",),
    # Consumer goods / food
    ("procter gamble", "procter & gamble", "p&g"),
    ("pepsico",),
    ("coca cola", "the coca cola company"),
    ("nestle",),
    ("unilever",),
    # Healthcare / pharma
    ("johnson johnson", "johnson & johnson", "jnj"),
    ("pfizer",),
    ("merck",),
    ("abbvie",),
    ("eli lilly", "lilly"),
    ("moderna",),
    ("amgen",),
    # Modern tech titans / unicorns
    ("uber",),
    ("lyft",),
    ("airbnb",),
    ("shopify",),
    ("spotify",),
    ("square", "block inc", "block"),
    ("stripe",),
    ("palantir",),
    ("snowflake",),
    ("databricks",),
    ("atlassian",),
    ("zoom",),
    ("slack",),
    ("okta",),
    ("cloudflare",),
    ("twilio",),
    ("datadog",),
    ("mongodb",),
    ("gitlab",),
    ("hashicorp",),
    ("confluent",),
    ("elastic",),
    ("crowdstrike",),
    ("palo alto networks",),
    ("zscaler",),
    ("snap",),
    ("pinterest",),
    ("reddit",),
    ("roblox",),
    ("doordash",),
    ("instacart",),
    ("coinbase",),
    ("robinhood",),
    ("figma",),
    ("dropbox",),
    ("box",),
    ("affirm",),
    ("discord",),
)


def search(client: httpx.Client, query: str, location: str | None,
           limit: int, remote_only: bool, posted_after_days: int = 30) -> list[JobPosting]:
    jobs = search_companies(
        client,
        query,
        location,
        limit,
        remote_only,
        allowed_alias_groups=FORTUNE_500_ALIAS_GROUPS,
        posted_after_days=posted_after_days,
    )
    return [job.model_copy(update={"source": NAME}) for job in jobs]
